POST http://localhost:8080/api/v1/registration/update
Content-Type: application/json

{
  "id": 1,
  "medId": 1,
  "docId": 1,
  "rdate": "2020-06-27",
  "cost": 100.1
}

###
GET http://localhost:8080/api/v1/registration?id=1
Accept: application/json

###
GET http://localhost:8080/api/v1/department?id=1
Accept: application/json

###