
POST http://localhost:8080/api/v1/mb/update
Content-Type: application/json
{
  "id": 6,
  "regId": 2,
  "edate": "2020-06-27"
}

###
GET http://localhost:8080/api/v1/mb?id=1
Accept: application/json

###
GET http://localhost:8080/api/v1/mb/reg?id=2
Accept: application/json

###
GET http://localhost:8080/api/v1/exab?id=1
Accept: application/json

###
GET http://localhost:8080/api/v1/exab/reg?id=2
Accept: application/json

###
POST http://localhost:8080/api/v1/exab/update
Content-Type: application/json
{
  "id": 9,
  "regId": 2,
  "edate": "2020-06-27"
}

###
POST http://localhost:8080/api/v1/medicinetable/insert
Content-Type: application/json

{
  "id": 8,
  "medId": 1,
  "medId2": 1,
  "count": 112
}

###
GET http://localhost:8080/api/v1/medicinetable?id=1
Accept: application/json

###
GET http://localhost:8080/api/v1/ranks?id=1
Accept: application/json

###
POST http://localhost:8080/api/v1/registration/update
Content-Type: application/json

{
  "id": 5,
  "medId": 1,
  "docId": 1,
  "rdate": "2020-06-27",
  "cost": 100.1
}

###
GET http://localhost:8080/api/v1/registration?id=1
Accept: application/json



###
GET http://localhost:8080/api/v1/doctor?id=2
Accept: application/json

###
GET http://localhost:8080/api/v1/doctor/ran?id=2
Accept: application/json

###
GET http://localhost:8080/api/v1/doctor/dep?id=2
Accept: application/json

###
POST http://localhost:8080/api/v1/ExaminationTable/exa
Content-Type: application/json

{
  "id": 6,
  "exaId": 1,
  "exaId2": 1
}

###
GET http://localhost:8080/api/v1/ExaminationTable?id=1
Accept: application/json

###